// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "TreeSitterLanguages",
    products: [
        .library(name: "TreeSitterLanguagesCommon", targets: ["TreeSitterLanguagesCommon"]),
        .library(name: "TreeSitterBash", targets: ["TreeSitterBash"]),
        .library(name: "TreeSitterBashQueries", targets: ["TreeSitterBashQueries"]),
        .library(name: "TreeSitterC", targets: ["TreeSitterC"]),
        .library(name: "TreeSitterCQueries", targets: ["TreeSitterCQueries"]),
        .library(name: "TreeSitterCSharp", targets: ["TreeSitterCSharp"]),
        .library(name: "TreeSitterCSharpQueries", targets: ["TreeSitterCSharpQueries"]),
        .library(name: "TreeSitterCPP", targets: ["TreeSitterCPP"]),
        .library(name: "TreeSitterCPPQueries", targets: ["TreeSitterCPPQueries"]),
        .library(name: "TreeSitterCSS", targets: ["TreeSitterCSS"]),
        .library(name: "TreeSitterCSSQueries", targets: ["TreeSitterCSSQueries"]),
        .library(name: "TreeSitterElixir", targets: ["TreeSitterElixir"]),
        .library(name: "TreeSitterElixirQueries", targets: ["TreeSitterElixirQueries"]),
        .library(name: "TreeSitterGo", targets: ["TreeSitterGo"]),
        .library(name: "TreeSitterGoQueries", targets: ["TreeSitterGoQueries"]),
        .library(name: "TreeSitterHTML", targets: ["TreeSitterHTML"]),
        .library(name: "TreeSitterHTMLQueries", targets: ["TreeSitterHTMLQueries"]),
        .library(name: "TreeSitterJava", targets: ["TreeSitterJava"]),
        .library(name: "TreeSitterJavaQueries", targets: ["TreeSitterJavaQueries"]),
        .library(name: "TreeSitterJavaScript", targets: ["TreeSitterJavaScript"]),
        .library(name: "TreeSitterJavaScriptQueries", targets: ["TreeSitterJavaScriptQueries"]),
        .library(name: "TreeSitterJSDoc", targets: ["TreeSitterJSDoc"]),
        .library(name: "TreeSitterJSDocQueries", targets: ["TreeSitterJSDocQueries"]),
        .library(name: "TreeSitterJSON", targets: ["TreeSitterJSON"]),
        .library(name: "TreeSitterJSONQueries", targets: ["TreeSitterJSONQueries"]),
        .library(name: "TreeSitterMarkdown", targets: ["TreeSitterMarkdown"]),
        .library(name: "TreeSitterMarkdownQueries", targets: ["TreeSitterMarkdownQueries"]),
        .library(name: "TreeSitterOCaml", targets: ["TreeSitterOCaml"]),
        .library(name: "TreeSitterOCamlQueries", targets: ["TreeSitterOCamlQueries"]),
        .library(name: "TreeSitterPerl", targets: ["TreeSitterPerl"]),
        .library(name: "TreeSitterPerlQueries", targets: ["TreeSitterPerlQueries"]),
        .library(name: "TreeSitterPHP", targets: ["TreeSitterPHP"]),
        .library(name: "TreeSitterPHPQueries", targets: ["TreeSitterPHPQueries"]),
        .library(name: "TreeSitterPython", targets: ["TreeSitterPython"]),
        .library(name: "TreeSitterPythonQueries", targets: ["TreeSitterPythonQueries"]),
        .library(name: "TreeSitterRegex", targets: ["TreeSitterRegex"]),
        .library(name: "TreeSitterRegexQueries", targets: ["TreeSitterRegexQueries"]),
        .library(name: "TreeSitterRuby", targets: ["TreeSitterRuby"]),
        .library(name: "TreeSitterRubyQueries", targets: ["TreeSitterRubyQueries"]),
        .library(name: "TreeSitterRust", targets: ["TreeSitterRust"]),
        .library(name: "TreeSitterRustQueries", targets: ["TreeSitterRustQueries"]),
        .library(name: "TreeSitterSwift", targets: ["TreeSitterSwift"]),
        .library(name: "TreeSitterSwiftQueries", targets: ["TreeSitterSwiftQueries"]),
        .library(name: "TreeSitterTSX", targets: ["TreeSitterTSX"]),
        .library(name: "TreeSitterTSXQueries", targets: ["TreeSitterTSXQueries"]),
        .library(name: "TreeSitterTypeScript", targets: ["TreeSitterTypeScript"]),
        .library(name: "TreeSitterTypeScriptQueries", targets: ["TreeSitterTypeScriptQueries"]),
        .library(name: "TreeSitterYAML", targets: ["TreeSitterYAML"]),
        .library(name: "TreeSitterYAMLQueries", targets: ["TreeSitterYAMLQueries"])
    ],
    dependencies: [],
    targets: [
        .target(name: "TreeSitterLanguagesCommon"),
        .target(name: "TreeSitterBash",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterBashQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterC",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterCQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterCSharp",
                exclude: ["src/grammar.json", "src/node-types.json", "src/binding.cc"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterCSharpQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterCPP",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterCPPQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterCSS",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterCSSQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterElixir",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterElixirQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterGo",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterGoQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterHTML",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterHTMLQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterJava",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterJavaQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterJavaScript",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterJavaScriptQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterJSDoc",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterJSDocQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterJSON",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterJSONQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterMarkdown",
                exclude: ["src/grammar.json", "src/node-types.json", "src/tree_sitter_markdown"],
                sources: ["src/scanner.cc", "src/parser.c"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterMarkdownQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterOCaml",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterOCamlQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterPerl",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterPerlQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterPHP",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterPHPQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterPython",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterPythonQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterRegex",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterRegexQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterRuby",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterRubyQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterRust",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterRustQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterSwift", cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterSwiftQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterTSX",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterTSXQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterTypeScript",
                exclude: ["src/grammar.json", "src/node-types.json"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterTypeScriptQueries", resources: [.copy("queries")]),
        .target(name: "TreeSitterYAML",
                exclude: ["src/grammar.json", "src/node-types.json", "src/schema.generated.cc"],
                cSettings: [.headerSearchPath("src")]),
        .target(name: "TreeSitterYAMLQueries", resources: [.copy("queries")])
    ]
)
